project:
  type: website
  output-dir: docs

website:
  title: "Tai Fowler"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Thesis
        href: thesis.qmd
      - text: CV
        href: media/tai_fowler_cv.pdf
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/tai-fowler
        target: _blank
      - icon: github
        text: GitHub
        href: https://github.com/megatai007
        target: _blank 
      - icon: envelope
        text: Email
        href: mailto:tai.c.fowler@gmail.com
  page-footer:
      background: primary
      left: Copyright 2026, Tai Fowler
format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.css
    toc: true



