project:
  type: website
  output-dir: docs

website:
  title: "Tai Fowler"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd        
      - text: Thesis
        href: thesis.qmd
      - text: CV
        href: media/master_resume.pdf
      - text: Resources
        href: resources.qmd
      - icon: linkedin
        text: LinkedIn
        href: www.linkedin.com/in/tai-fowler
        target: _blank
      - icon: github
        text: GitHub
        href: https://github.com/megatai007
        target: _blank 
      - icon: envelope
        text: Email
        href: mailto:tai.c.fowler@gmail.com
  page-footer:
      background: dark 
      left: Copyright 2026, Tai Fowler
format:
  html:
    theme: styles.csss
    css: styles.css
    toc: true
    page-layout: full



